Sample profiles
Two sample profiles are included in C.2 and C.3. They illustrate what a
profile is and how a profile shall be documented. While these profiles are
ready to use and conform to the ISO 19160-1 Core conformance class, data
prepared according to these profiles does not necessarily conform to ISO
19160-1 (data conformance is not specified). In C.4 a number of diagrams from
other profiles are included to provide further examples of profiles.

C.2 Example 1: Minimal address profile

The minimal address profile represents minimal addresses, i.e. addresses as
they are used colloquially, without any additional information, such as
identifiers, coordinates or metadata. This example is included to illustrate
that even though the address model allows complexity, it can also be used to
represent addresses comprising of address lines (character strings) only.


Define default value types.

* CharacterString
* Integer


NECESSARY OBJECTS:

1. DEFAULT VALUE TYPES
2. DERIVED VALUE TYPES
3. COMPONENT CLASSES
4. ADDRESS CLASSES

5. RENDER CLASSES / TEMPLATES

Conditions? Enumerated choices?
Locales/Scripts - one duplicate for each


What do people do with addresses?

Specific use cases:
* electronic commerce : entering shipping address
* business cards: 

Our office address:

Full address:
Suites 1107-1111,
Floor 11,
Central Building,
1-3 Pedder Street,
Central,
Central & Western District,
Hong Kong Island,
Hong Kong

OR:

Suites 1107-1111,
Floor 11,
Central Building,
28-30 Queen's Road Central,
Central,
Central & Western District,
Hong Kong Island,
Hong Kong

Preferred address, as equally understandable (and deliverable):
Suite 1111,
1 Pedder Street,
Central,
Hong Kong


香港
中環
畢打街一號
中建大廈
十一樓
一一一一室

香港
中西區
中環
畢打街一至三號
中建大廈
十一樓
一一零七至一一一一室


* Address as an identity: loss or additional details. Some omit unit or district information
  information, or street information. "Preference", but of whom?
* Address as destination
* Address as locator (geographic location)
* Address as routing information (address classes)

Inputting an address
Outputting an address


Partially structured address


ValueTypes: ISO 19103.


What does a profile contain?

* attributes
** AddressClasses
** TemplateClasses, each AddressClass should provide a TemplateClass (same or inner level)

* metadata
** ID
** TYPE
** PUBLISHER (signature, URI...)
** DESCRIPTION
** LOCALE/SCRIPT info

* validation information
* status


19160-1 Example 1.

----
profile = {

  id: "http://www.iso.org/tc211/tc211-minimal.adp",
  type: "iso-19160-address-profile",
  publisher: "http://www.iso.org/tc211/",
  signature: "...",

  name: "TC 211 Minimal Address Profile",
  locale: {
    language: "en",
    script: "en",
  },

  addressComponents: {
    addressLine: {
      valueType: CharacterString,
      minCardinality: 1,
      maxCardinality: n
    },
  },

  addressClasses: {
    minimalAddress: {
      availableFields: [
        {
          componentType: addressLine,
          min: 1,
          max: n,
          description: "One line of this address",
          require: true,
        }
      ],
      showTemplates: [
        {
          /* TODO */
          orientation: horizontal,
          text: "({{ addressLine }}\n)*"
          }
        }
      ]
    }
  }
}
----

----
addressInstance1 = {
  profile: "http://www.iso.org/tc211/tc211-minimal.adp",
  components: [
    {
      type: addressLine,
      value: 14 Church Street,
    },
    {
      type: addressLine,
      value: Hatfield
    },
    {
      type: addressLine,
      value: South Africa
    }
  ]
}

addressInstance2 = {
  profile: "http://www.iso.org/tc211/tc211-minimal.adp",
  components: [
    {
      type: addressLine,
      value: Statue of Liberty
    },
    {
      type: addressLine,
      value: Liberty Island
    },
    {
      type: addressLine,
      value: New York
    },
    {
      type: addressLine,
      value: NY
    }
  ]
}
----



19160-1 Example 2.

----
profile = {

  id: "http://www.iso.org/tc211/tc211-sample.adp",
  type: "iso-19160-address-profile",
  publisher: "http://www.iso.org/tc211/",
  signature: "...",

  name: "TC 211 Minimal Address Profile",
  locale: {
    language: "en",
    script: "en",
  },

  valueTypes: {
    addressNumberValue: {
      primitiveType: Integer,
      maxValue: 10000,
      minValue: 1,
    },
    boxNumberValue: {
      primitiveType: Integer,
      maxValue: 100000,
      minValue: 1,
    }
  }

  addressComponents: {
    addressNumber: {
      valueType: addressNumberValue,
    },
    boxNumber: {
      valueType: boxNumberValue,
    },

    /* Table C.3. Address component type */
    thoroughfareName: {
      valueType: thoroughfareNameValue,
    },
    localityName: {
      valueType: CharacterString,
    },
    postOfficeName: {
      valueType: CharacterString
    },
    postCode: {
      valueType: CharacterString
    },
    countryName: {
      valueType: thoroughfareName,
    }
    addressNumber: {
      valueType: addressedObjectIdentifier,
    },
  },

  addressClasses: {
    streetAddress: {
      description: Street Address,
      availableFields: [
        {
          componentType: addressNumber,
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: thoroughfareName,
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: placeName
          valueType: CharacterString,
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: postCode
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: countryName
          minCardinality: 1,
          maxCardinality: 1,
          required: false,
        },
      ],
      showTemplates: [
        {
          /* TODO */
        }
      ]
    },
    boxAddress: {
      availableFields: [
        {
          componentType: boxNumber,
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: postOfficeName,
          valueType: CharacterString,
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: postCode
          minCardinality: 1,
          maxCardinality: 1,
          required: true,
        },
        {
          componentType: countryName
          minCardinality: 1,
          maxCardinality: 1,
          required: false,
        },
      ],
      showTemplates: [
        {
          /* TODO */
        }
      ]
    }
  }
}
----

----
addressInstance1 = {
  profile: "http://www.iso.org/tc211/tc211-sample.adp#streetAddress",
  components: [
    {
      type: addressNumber,
      value: 99
    },
    {
      type: thoroughfareName,
      value: {
        name: Lombardy,
        type: Street
      }
    },
    {
      type: placeName,
      value: The Hills,
    },
    {
      type: postCode,
      value: 0039,
    },
    {
      type: countryName,
      value: South Africa
    }
  ]
}

boxInstance1 = {
  profile: "http://www.iso.org/tc211/tc211-sample.adp#boxAddress",
  components: [
    {
      type: boxNumber,
      value: 345
    },
    {
      type: postOfficeName,
      value: Orlando,
    },
    {
      type: postCode,
      value: 2020
    },
    {
      type: countryName,
      value: South Africa
    }
  ]
}

----

addressClass
addressComponentType
addressComponentTypeValue -> primitive value type

addressableObjectType



Sample address
Profile
| commercialBuilding | Commercial Buildling
| landParcel | Land parcel
| postBox | Post box in the post office building
| residentialDwelling | Residential dwelling


* Free form
* Input form
* Normalized form


Template rendering:
SVG with replacable variables
Fields


Unstructured -> Structured -> Verified

Each field:
* max occur
* max length / min length
* Largest num smallest num
* mandatory / optional


