image:
  name: metanorma/metanorma
  entrypoint: [""]

cache:
  paths:

build:
  stage: build
  script:
    - bundle add metanorma-standoc --git https://github.com/metanorma/metanorma-standoc --branch 73487c2572ee30af9e84b0f447c2bf1bd64fd554
    - bundle
    - curl -sSL https://raw.githubusercontent.com/kata-containers/runtime/master/.ci/install-yq.sh | bash
    - cp ~/go/bin/yq /usr/local/bin/
    - make clean all
    - make published
    - mv published public
  artifacts:
    paths:
      - public

pages:
  dependencies:
    - build
  stage: deploy
  script:
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=build"'
  artifacts:
    paths:
      - public
  only:
    - master
