'******* STATES RELATIONS *********************************************
note top: Creation of an\n interchange\n address profile
(*) --> "Published"
--> "Valid for use"
"Published" --> "Retired"
"Valid for use" --> "Retired"
"Valid for use" -->[Update] "Valid for use"
