@startuml

!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class Localization{
  +locale: PT_Locale { characterEncoding = UTF8 }
  +script: iso15924Code
  +textDirection: TextDirectionCode
}

enum TextDirectionCode <<enumeration>> {
  leftToRight
  rightToLeft
  topToBottom
}

class Validity{
  +validityBegins: CI_Date { dateType = validityBegins }
  +validityEnds: CI_Date { dateType = validityEnds }
  +revision: CI_Date { dateType = revision }
}

class Signature{
  +algorithm: iso14888Oid
  +publicKey
  +signature: CharacterString
}

'******* NOTES ********************************************************


'******* CLASS RELATIONS **********************************************
Signature -[hidden]-> Localization
Localization -[hidden]-> Validity

@enduml