
[source=ISO19160-1]
== Terms and definitions

=== address interchange object
alt:[AXO]

digital objects for address interchange defined in ISO 19160-6


=== lineage

provenance, source(s) and production process(es) used in producing a resource

[.source]
<<ISO19115-1,clause="4.9">>


=== profile

set of one or more base standards or subsets of base standards, and,
where applicable, the identification of chosen clauses, classes,
options and parameters of those base standards, that are necessary for
accomplishing a particular function

[.source]
<<ISO19106,clause="4.5">>


=== data type

specification of a value domain with operations
allowed on values in this domain

[.source]
<<ISO19103,clause="4.14">>


=== primitive data type

{{data type}} that has no super type

NOTE: The primitive data type of a data type is the data type itself, if the
data type has no super type, and otherwise the primitive data type of the super
type of the data type.

[.source]
<<ISOIEC10179,clause="4.23">>, removal of initial "A", moved second sentence
into Note to entry.


=== interchange address

address data compliant to an {{interchange address}} class profile


[[term-address-feature]]
=== address feature

marking on an {{interchange address}} to indicate what it is capable of


[[term-address-layout-template]]
=== address layout template

specification of layout and positioning of address components for interchange
addresses

=== address display template

{{address layout template}} for the display of {{interchange address,interchange addresses}}

=== address form template

{{address layout template}} of an input form for the entry of
{{interchange address,interchange addresses}}

[[term-address-processor]]
=== address processor

entity that processes {{interchange address,interchange addresses}}


[[term-address-profile-distributor]]
=== address profile distributor

entity that distributes interchange address profiles


=== digital signature
alt:[signature]

data appended to, or a cryptographic transformation of, a data unit that allows
the recipient of the data unit to verify the source and integrity of the data
unit

[.source]
<<ISO-IEC_9798-3,clause="3.3">>

=== private signature key

private key which defines the private signature transformation

NOTE: This is sometimes referred to as a secret signature key.

[.source]
<<ISO-IEC_9798-1,clause="3.23">>

=== public verification key

public key which defines the public verification transformation

[.source]
<<ISO-IEC_9798-1,clause="3.28">>

=== object identifier
alt:[OID]

globally unique value associated with an object to unambiguously identify it

[.source]
<<ISO-IEC_29149-2012,clause="2.11">>

[[term-language-id]]
=== language identifier
alt:[language symbol]

symbol that uniquely identifies a particular language

[.source]
<<ISO639-3,clause="3.3">>

[[term-script]]
=== script

set of graphic characters used for the written form of one or more languages

[.source]
<<ISO15924,clause="3.7">>

[[term-script-code]]
=== script code

combination of characters used to represent the name of a {{script}}

[.source]
<<ISO15924,clause="3.8">>


=== Uniform Resource Identifier
alt:[URI]

unique identifier for a resource, structured in conformance with IETF RFC 2396

NOTE: The general syntax is `<scheme>::<scheme-specific-part>`. The hierarchical
syntax with a namespace is `<scheme>://<authority><path>?<query>` — see RFC
2396.

[.source]
<<ISO_19136-1,clause="3.1.62">>
