
== Conformance

=== General

This part of ISO {docnumber} defines four classes of requirements and
conformance. <<Annex-A>> specifies how conformance with these classes
shall be tested.

=== Address profile register

To conform to this standard, an address profile register shall satisfy all of
the requirements specified for a register in <<ISO19135-1>>. See
<<test-profile-register>>.


=== IxAddressProfile

Any machine-readable description of an <<ISO19160-1>> profile for which conformance
is claimed shall pass all the requirements described in the abstract test suite in
<<test-ix-address-profile>>.


=== IxAddressClass

Any machine-readable description of an <<ISO19160-1>> address class for which
conformance is claimed shall pass all the requirements described in the
abstract test suite in <<test-ix-address-class>>.


=== IxAddressComponent

Any machine-readable description of an <<ISO19160-1>> address component for
which conformance is claimed shall pass all the requirements described in the
abstract test suite in <<test-ix-address-component>>.


=== IxAddressInstance

Any instance of IxAddressProfile class for which
IxAddressInstance conformance is claimed shall pass the requirements
described in the abstract test suite in <<test-ix-address-instance>>.

=== FormTemplate

Any FormTemplate in Interchange Address Profile model for which
FormTemplate conformance is claimed shall pass the requirements
described in the abstract test suite in <<test-form-template>>.

=== DisplayTemplate

Any DisplayTemplate in Interchange Address Profile model for
which DisplayTemplate conformance is claimed shall pass the
requirements described in the abstract test suite in <<test-display-template>>.
