
== Address profile registry

=== General

The ISO address profile registry will be managed with version control software,
publicly available with an API and/or a graphical user interface, such as a web-based interface,
to satisfy both programatic and human use for the dissemination, display and management
of the registry.

The ISO address profile register is a non-hierarchical register. References to principal registers and sub registers are excluded from this document.

This address profile registry follows the requirements specified in
<<ISO19135-1>>, and additional requirements specified in this standard.

Rules for managing a register of geographical information items, including the submission of information, are found in <<ISO19135-1,clause=6>>.

NOTE: Reference to the <<ISO19135-1>> requirement is denoted by ɳ (i.e. [ɳ2] = Requirement 2).


=== Roles and responsibilities in the management of an address profile registry

The roles and responsibilities of the register owner, register manager, submitting organizations,
control body, registry manager and register user are set out in <<ISO19135-1>>.

Requirement 1 [ɳ1]: The register owner shall set terms and conditions regarding different levels of access to the register and making the contents available to the public. In addition, the register owner shall specify the time period in which the approval process shall be completed.

Requirement 2 [ɳ2]: The register owner shall appoint a register manager. A register owner may serve as the register manager for any register that it has established or it may appoint another organization to serve as the register manager.

Requirement 3 [ɳ3]: The register owner shall decide whether a control body is required for the register and if so appoint the control body. The register owner may serve as the control body for any register that it has established or it may delegate that role to a subgroup within the organization or to the register manager.

Requirement 4 [ɳ4]: A register owner shall specify the criteria that determine which organizations may act as submitting organizations.

Requirement 5 [ɳ5]: The register owner shall clarify the process for a submitting organization to appeal decisions of the control body (if such a body is appointed). The register owner may establish a procedure for such a process. The specification of this procedure shall include appropriate time limits for completion of the process. An alternative solution may be for a submitting organization to resubmit a new proposal with changes or a better justification.

Requirement 6 [ɳ6]: A register manager shall manage a register in conformance with <<ISO19135-1,clause=6>>.

Requirement 7 [ɳ7]: Upon request, the register manager shall distribute an information package containing a description of the register and how to submit proposals for changes to the content of the register. The information package shall describe what proposed changes to the content may be considered to be substantive.

Requirement 8 [ɳ8]: The register manager shall accept proposals from submitting organizations and manage the proposals as specified in <<ISO19135-1,clause=6.4>>. The register manager shall pass proposals to the control body for decisions as to acceptability and shall serve as the point of contact between the control body and the submitting organization for negotiations regarding changes to the proposal.

Requirement 9 [ɳ9]: The register manager shall determine whether a submitting organization is
qualified in accordance with the criteria established by the register owner.

Requirement 10 [ɳ10]: If a control body is appointed, it shall accept proposals from the register manager and render a decision regarding each proposal within the time limits specified by the register owner.

Requirement 11 [ɳ11]: A registry manager shall ensure the integrity of any register held in the registry and shall provide means for electronic access to the registry for register managers, control body members, and register users.

Requirement 12 [ɳ12]: Register managers shall consider the requirements of different categories of users in selecting methods for publishing the content of a register.

Requirement 13: The ISO address profile register shall have a publicly available record of changes where historical content shall remain publicly available.

Submitting organizations for the ISO address profile register consist of organizations and/or persons responsible for defining and maintaining address profiles.


=== Unmodified ISO 19135-1:2015 requirements

The unmodified <<ISO19135-1>> requirements are as follows:

Requirement 14 [ɳ13]: Every register shall have a technical document describing the item classes to be registered.

NOTE: For the ISO address profile register that technical document is this document.

Requirement 15 [ɳ14]: Items shall be individually managed, moving through a set of well-defined states. Information about the temporal history of each item shall be maintained.

Requirement 16 [ɳ16]: A clarification shall not cause any substantive semantic or technical change to a registered item.

Requirement 17 [ɳ17]: Clarification shall be accomplished by updating the existing item in the register. The clarification shall be recorded with a justification of the change and the date on which the register transaction was made.

Requirement 18 [ɳ19]: Retirement shall be accomplished by leaving the item in the register, having its status changed to retired, and including the date on which the register transaction was made.

Requirement 19 [ɳ21]: The register manager shall review proposals received from third parties for completeness and return proposals to the submitting organization if the proposal is incomplete or if the submitting organization is not qualified, else initiate the approval process.

Requirement 20 [ɳ22]: The approval process shall be completed within the time period specified by the register owner.

Requirement 21 [ɳ23]: A registry manager shall ensure that information about valid, invalidated, superseded, or retired items in the register is readily available to users.


=== Modified ISO 19135-1:2015 requirements

The <<ISO19135-1>> requirements modified for this document are as follows:

Requirement 22 [ɳ15]: If an item is superseded by another item, the date the succession occurred shall be captured, along with references to and from the item that superseded it. At any given time, only one item in the series should be “valid”.

NOTE: The requirement that only one item in the series is "valid" is removed.

Requirement 23 [ɳ20]: If a register item is deemed to be no longer suitable for the use in the production of new data and has been superseded by a new register item, the original item shall remain in the register, shall have its status changed to superseded, have a reference to the item(s) that superseded it, including the date on which the register transaction was made.

NOTE: The option of removing a superseded item from the register is removed.

Requirement 24 [ɳ18]: If an item in a register is found to have substantive error, it shall be left in the register, have its status changed to invalid, have a reference to the item(s) that replaced it, and have the date when the register transaction was made.

NOTE: The option of removing an invalidated item from the register is removed.


=== Specific requirements

Requirement 25: The ISO address profile registry shall follow <<ISO19160-1,clause=6>>
in the management of address profiles, including the submission
of information.


=== Content requirements from ISO 19135-1:2015

The ISO address profile register shall conform to the core register schema in <<ISO19135-1,clause=7>>. This clause sets out specific requirements as follows:

NOTE: Reference to the <<ISO19135-1>> requirement is denoted by ɳ (i.e. [ɳ2] = Requirement 2).

Requirement 26 [ɳ24]: The core register shall conform to the register schema as specified in UML in <<ISO19135-1,clause=7>>.

Requirement 27 [ɳ25]: The attribute identifier that designates an item class held in a register that conforms to <<ISO19135-1,clause=7>>, shall uniquely denote the item class within the context of the register.

Requirement 28 [ɳ26]: The attribute `itemIdentifier` is represented as a `CharacterString` that is used to uniquely denote that item within an item class and is intended for information processing. Once a value has been assigned, it shall not be reused. The class/identifier union shall be unique within the register.
