
== Process of address profile and address interchange

Practical usage of AXO models relies on the establishment of an
address profile registry.

This clause sets out specific requirements in relation with <<ISO19135-1>>.

The roles and responsibilities of the register owner, register manager, submitting organizations, control body, registry manager and register user are set out in <<ISO19135-1,clause=5>>.

=== Address profiles

==== General

.Lifecycle of an address profile
[plantuml]
....
include::../models/AddressProfileLifeCycle.wsd[]
....

==== Creating address profiles and address class profiles

Address class profiles that comply with <<ISO19160-1,annex B>>,
<<ISO19106>> Conformance class 1, and requirements specified in
<<address-profile>> are created. Address class profiles
are created in accordance with requirements specified in
<<address-profile>>. Address class profiles are associated with
the corresponding address profile in accordance with requirements
specified in <<address-profile>>.

==== Publishing address profiles

Publishers distribute their address profiles to others
through direct exchange or through a registry.

==== Updating address profiles

Publishers can update an address profile and profiles associated with it,
and re-distribute it by publishing using a new version number that
supersedes the previously published one.

==== Using address profiles

Applications retrieve suitable address class profiles associated with corresponding
address profiles to:

* render address input forms according to the
profile-specified form template; or

* display addresses according to the profile-specified display template.

Applications shall consider the validity period of an address class profile,
and shall periodically check with the publisher (or a registry that
the publisher distributes via) the latest version of the address
profile.

==== Retiring address profiles

Publisher can indicate the validity period of an address class profile in the
profile itself, which if the validity end date has passed, would indicate
that the profile is retired.

To immediately retire an address class profile, the publisher shall
distribute a new version of the address profile with an expired
validity period.


=== Interchange address

==== General

.Lifecycle of an interchange address
[plantuml]
....
include::../models/AddressInstanceLifeCycle.wsd[]
....


==== Creating a profile-complaint address

This section describes how a profile-compliant address is created. The desired
address class profile shall be already retrieved for creating a profile-compliant
address that conforms to it.

Typically, a user enters an address through an
application interface that implements an input format that conforms to the
interchange address class profile's form template, such as an application that
runs on an operating system or an Internet application. Such input interface
may or may not provide a graphical form.

Conforming applications should not expect general users to be able to
input an address with a fully-deduced structure. Immediately after
input no features are marked on the interchange address.

==== Interchange of an interchange address

After a user inputs an address into a structured address form, the user
submits this address to the designated recipient, which could be an
e-retailer, an electronic business card, or a calendar event.

==== Displaying an interchange address

The recipient or service that receives an interchange address instance either
already has the interchange address class profile or should obtain the interchange
address class profile definition. With the interchange address class profile,
it could then display the interchange address according to the address class profile's
display template.

==== Adding address features

===== Improving quality of an interchange address

The recipient or service could process the address, such as to further
clean up the address by improving the conformance level by fully
deducing the address structure, which would add an address feature
"https://standards.iso.org/19160/-6/features/specified" to the
address instance.

To ensure that the resulting interchange address with a fully-specified
structure is correct, the processor may wish to confirm with the user
the resulting address, such as in the case where the address is used
for shipping information. This would add the `AddressFeature`
"https://standards.iso.org/19160/-6/features/confirmed" to the
address instance.

===== Verifying an interchange address

The recipient or service could further validate the address, such as
with a postal or addressing authority. This would add the
`AddressFeature` "https://verifyingauthority/verified" to the interchange address
written by the verifying authority.

==== Adding associated data to an interchange address

A processor of an interchange address could add extra information such as
delivery instructions or routes as associated data.

If the user already has a verified, structured address, then the
service could save the effort for verifying the address. Custom
address features could be added into the interchange address.

==== Discarding an interchange address

When a service no longer needs the address, it should be disposed of.
