[[introduction]]

:sectnums!:
== Introduction

=== Purpose

Addresses are among the most commonly exchanged information on the
Internet, and the interchange of them is crucial to a number of
Internet applications, such as electronic commerce, contact exchange,
non-postal deliveries, as well as location scheduling.

Yet, addresses can mean much more than just geolocation information:

*  as an identity, such as an office address;

*  as reference points (waypoints) in routing information; and

*  as a delivery point.

The interchange of address information requires a common structure of address data.

For instance, if a software application needs a user to input address
information, in order to produce a machine readable address that is
interoperable with other systems, the user would need assistance from
the application to enter the address in the correct format and structure.

This document specifies a set of data models that focuses on enabling
software applications the digital interchange of address profiles,
address instances and instructions for their input and display
suitable for machine encoding of address information. These models are
called the "`Address Interchange Object`" ("AXO") models.

Furthermore, a registry mechanism is defined to ensure the address profiles
can be made publicly available.

//geocodings of locations are out of scope in this standard.

=== Relationship with other parts of the ISO 19160 standards family

This standard complements the other parts in the family of ISO 19160 standards:

* <<ISO19160-1>> describes conceptual models for addressing that allow
specification of international address profiles. This document
further provides methods to utilize these models in a way
suitable for digital interchange and storage.

* <<ISO19160-4>> defines key terms for postal addressing, postal address
components and constraints on their use. It focuses on use cases for postal
applications, specifying the methods to write or detect addresses on mail items.
This documents adapts models from <<ISO19160-1>>
as address interchange models, to facilitate interchange and interaction
of addresses between humans and applications, and between applications,
and for applications to interact and interchange international addresses,
while supporting human input and human-machine interaction, without loss
of fidelity.

* ISO 19160-5 focuses on the rendering of addresses for different devices
with a focus on their representations on maps, virtual and augmented reality.
This document focuses on providing an interoperable data model for the
interchange and storage of address profiles and addresses, as well as
the input and rendering of compliant addresses in a normalized manner.
This approach results into a scheme that can be understood across the
spectrum of address consumers, including humans, applications, devices and
systems.

=== Address as entered data

The lifecycle of an address entry exchanged on the Internet typically
starts with manual input of a human actor. This data, structured or
unstructured, is then submitted to an Internet-connected application,
and the application may in turn transmit this information to other
applications or external parties on behalf of the user who provided the
address.

This transmission is usually performed to fulfil service
delivery to the user. Within the process, there may be machine-human
interactions that require display of the address in human-readable
form, as well as machine-to-machine interactions on the address, such
as for data validation.

Additional caution shall be placed on the accuracy (or lack thereof) of
human input addresses. While an address specified by a human actor may
unambiguously distinguish a location, there may be intention or
unintentional omissions or additions to an "`official`" address (if there
was one).

=== Relationship to the addressable object

Attributes of the object which the address points to are considered
out of scope of this document, including the `AddressableObject` model
specified in <<ISO19160-1>>.

While considered orthogonal to the AXO models, `AddressableObject` and
other simliar models can easily be used together with the AXO models.

[example]
In a navigation map, an AXO address can point to an addressable object,
in which provides a list of its extant facilities.
