
[[AnnexB]]
[appendix,obligation=informative]
== Usage

=== Accuracy and verification

An authority, such as the local post office, could "`verify`" a
structured address that it is confirmed that this address instance is a
"`deliverable address`" through an `AddressFeature`.

[source=Ronald Tse]
****
Link to the OGC geocoding API SWG?
****

The owner of the address, such as the tenant of an office, could
provide its signed, structured address on an electronic business card.
This allows the recipient of the business card to know whether the
senders address is authentic. If this address is verified to be a
"`deliverable address`", the recipient will know that items sent to this
address will very likely be deliverable.

Extra steps need to be taken here to allow this.

=== Address as identity

Addresses do not only specify a location, in some cases they are part
of the identity. For example, in business cards, an address can mean
more than just an address, such as with vanity value.

This document shall support this functionality for it to be useful in
contact exchange.

This address represents a complete textual address instance.

[source]
----
Suite 1109,
Floor 11,
Central Building,
1-3 Pedder Street,
Central,
Central & Western District,
Hong Kong Island,
Hong Kong
----

And this address represents the identical address as above,
with a reduction of information that is already implied,
which that does not reduce its correctness. This can be
achieved by supplying a `displayTemplate` in the
interchange address.

[source]
----
Suite 1109,
1 Pedder Street,
Central,
Hong Kong
----


=== Address as destination

In certain cases, an address is expected to be reachable either by
person and/or post.

An address instance should support being used in conjunction with
routing information, acting as a waypoint, and/or supporting a
source-defined route.

[example]
Written instructions on how to deliver to a place can be unambiguous,
but terribly difficult to locate.
For instance, some buildings have split floors -- rooms may have the same floor
identifier, but is actually inaccessible from the same floor.
