
[[terms]]
== Terms and Definitions

[[term-address]]
=== address

structured information that allows the unambiguous determination of an
object for purposes of identification and location

[.source]
<<ISO19160-1>>

[[term-addressable-object]]
=== addressable object

object that may be assigned an _address_ (<<term-address>>)

[.source]
<<ISO19160-1>>


[[term-address-class]]
=== address class

description of a set of addresses that share the same address
components, operations, methods, relationships, and semantics

[.source]
<<ISO19160-1>>


[[term-ix-address-class]]
=== interchange address class

representation of an _address class_ (<<term-address-class>>)
suitable for interchange


[[term-address-component]]
=== address component

constituent part of an _address_ (<<term-address>>)

[.source]
<<ISO19160-1>>

[[term-ix-address-component]]
=== interchange address component

representation of an _address component_ (<<term-address-component>>)
suitable for interchange


[[term-lineage]]
=== lineage

_provenance_ <<term-provenance>>, source(s) and production process(es) used
in producing a resource

[.source]
<<ISO19115-1,clause 4.9>>

[[term-locale]]
=== locale

definition of the subset of a user's environment that depends on
language and cultural conventions

[.source]
<<ISO9945,clause 4.211>>, The notes given in ISO/IEC/IEEE 9945:2009 for this
entry have been omitted.

[[term-parent-address]]
=== parent address
_address_ (<<term-address>>) of a _parent addressable object_
(<<term-parent-addressable-object>>)


[[term-parent-addressable-object]]
=== parent addressable object

_addressable object_ (<<term-addressable-object>>) that fully encloses one
or more other addressable objects


[[term-profile]]
=== profile

set of one or more base standards or subsets of base standards, and,
where applicable, the identification of chosen clauses, classes,
options and parameters of those base standards, that are necessary for
accomplishing a particular function

[.source]
<<ISO19106,clause 4.5>>

[[term-ix-address-profile]]
=== interchange address profile

_profile_ (<<term-profile>>) that contains data requirements
and layout templates for multiple _address classes_


[[term-ix-address-instance]]
=== interchange address instance

an _address_ (<<term-address>>) that is set within the context of an
_interchange address class_ (<<term-ix-address-class>>)


[[term-provenance]]
=== provenance

organization or individual that created, accumulated, maintained
and used records

[[term-data-type]]
=== data type

specification of a value domain (<<ISO19103,clause 4.37>>) with operations
(<<ISO19103,clause 4.26>>) allowed on values in this domain

[.source]
<<ISO19103,clause 4.14>>

[[primitive-data-type]]
=== primitive data type

data type (<<term-data-type>>) defined as "`Primitive Type`"
in <<ISO19103,section 7.2>>


[[term-ud-data-type]]
=== user defined data type

_data type_ (<<term-data-type>>) defined by the user in an
_interchange address profile_ (<<term-ix-address-profile>>)
through the composure of other
_data types_ (<<term-data-type>>) and constraints

[[term-ud-data-type-def]]
=== user defined data type definition

definition of a _user defined data type_
(<<term-ud-data-type>>)

[[term-address-capability]]
=== address capability

marking on an _address instance_ (<<term-ix-address-instance>>) to indicate its
status


[[term-address-layout-template]]
=== address layout template

specification of layout and positioning of
_address components_ (<<term-address-component>>)
for an _interchange address instance_ (<<term-ix-address-instance>>)
of an _address class_ (<<term-address-class>>)

=== address display template

address layout template (<<term-address-layout-template>>)
for the display of _interchange address instances_ (<<term-ix-address-instance>>)
of an _address class_ (<<term-address-class>>)

=== address form template

address layout template (<<term-address-layout-template>>)
of an input form for the entry of
_interchange address instances_ (<<term-ix-address-instance>>)
of an _address class_ (<<term-address-class>>)

[[term-address-processor]]
=== address processor

entity that processes _interchange address instances_ (<<term-ix-address-instance>>)


[[term-address-profile-distributor]]
=== address profile distributor

entity that distributes _interchange address profiles_ (<<term-ix-address-profile>>)


[[term-signature]]
=== signature

the string of bits resulting from the signature process

[.source]
<<ISO14888-3,clause 4.15>>

[[term-signature-key]]
=== signature key

a secret data item specific to an entity and usable only by this entity
in the signature process

[.source]
<<ISO14888-3,clause 4.18>>

[[term-verification-key]]
=== verification key

a data item which is mathematically related to an entity's
_signature key_ (<<term-signature-key>>) and which is used by
the verifier in the verification process

[.source]
<<ISO14888-3,clause 4.15>>

[[term-oid]]
=== object identifier
[alt]#oid#

a value (distinguishable from all other such values) which is associated with an object

[.source]
<<ISO15961,clause 3.1.16>>

[[term-language-id]]
=== language identifier
[alt]#language symbol#

symbol that uniquely identifies a particular language

[.source]
<<ISO639-3,clause 3.3>>

[[term-script]]
=== script

set of graphic characters used for the written form of one or more languages

[.source]
<<ISO15924,clause 3.7>>

[[term-script-code]]
=== script code

combination of characters used to represent the name of a _script_ (<<term-script>>)

[.source]
<<ISO15924,clause 3.8>>

[[term-uri]]
=== URI

uniform resource identifier

[.source]
<<ISO19103,clause 5.3>>

