[[introduction]]

:sectnums!:
== Introduction

Addresses are among the most commonly exchanged information on the
Internet, and the interchange of them is crucial to a number of
Internet applications, such as electronic commerce, contact exchange,
non-postal deliveries, as well as location scheduling.

Yet, addresses can mean much more than just geolocation information:

*  As an identity, such as an office address

*  As reference points (waypoints) in routing information

*  As a delivery point

This standard differentiates from and complements to other parts in the
family of ISO 19160.

<<ISO19160-1>> describes the Addressing Conceptual models that allow
specification of international address profiles, and this International
Standard further provides methods to utilize them in a way suitable for
electronic interchange.

<<ISO19160-4>> defines key terms for postal addressing, postal address
components and constraints on their use. It focuses use cases of postal
applications specifying the methods to write or detect addresses on mail items.
This standard, ISO 19160-6, however, adapts models from <<ISO19160-1>>
as Address Interchange models, to facilitate interchange and interaction
of addresses between humans and applications, and between applications,
and for applications to interact and interchange international addresses,
while supporting human input and human-machine interaction, without loss
of fidelity.

<<ISO19160-5>> describes how to represent addresses on different devices. It
targeted on all addresses but was concluded to be too complex. This standard,
ISO 19160-6, therefore, focuses on a subset by providing templates for the
serialization of address objects and address input, and representation by
creating address exchange objects.

The lifecycle of an address entry exchanged on the Internet typically
starts with manual input of a human actor. This data, structured or
unstructured, is then submitted to an Internet-connected application,
and the application may in turn transmit this information to other
applications or external parties on behalf of the user who provided the
address. This transmission is usually performed to fulfil service
delivery to the user. Within the process, there may be machine-human
interactions that require display of the address in human-readable
form, as well as machine-to-machine interactions on the address, such
as for data validation.

Additional caution shall be placed on the accuracy (or lack thereof) of
human input addresses. While an address specified by a human actor may
unambiguously distinguish a location, there may be intention or
unintentional omissions or additions to an "`official`" address (if there
was one).

The models in this document depends on data models defined
in <<ISO19115-1>> and <<ISO19157>>.



