[[introduction]]

:sectnums!:
== Introduction

Addresses are among the most commonly exchanged information on the
Internet, and the interchange of them is crucial to a number of
Internet applications, such as electronic commerce, contact exchange,
non-postal deliveries, as well as location scheduling.

Yet, addresses mean much more than just geolocation information:

*  As an identity, such as an office address

*  As reference points (waypoints) in routing information

*  As a delivery point

The lifecycle of an address entry exchanged on the Internet typically
starts with manual input of a human actor. This data, structured or
unstructured, is then submitted to an Internet-connected application,
and the application may in turn transmit this information to other
applications or external parties on behalf of the user who provided the
address. This transmission is usually performed to fulfil service
delivery to the user. Within the process, there may be machine-human
interactions that require display of the address in human-readable
form, as well as machine-to-machine interactions on the address, such
as for data validation.

Additional caution shall be placed on the accuracy (or lack thereof) of
human input addresses. While an address specified by a human actor may
unambiguously distinguish a location, there may be intention or
unintentional omissions or additions to an "official" address (if there
was one).

This International Standard facilitates the interchange and interaction
of addresses between humans and applications, and between applications,
through the specification of a defined syntax for applications to
interact and interchange international addresses, while supporting
human input and human-machine interaction, without loss of fidelity.

// TODO: clean up introduction

Specifically, this document describes an encoding for a profile of the Addressing Conceptual model in <<ISO19160-1>>.

The models in this document depends on data models defined
in <<ISO19115-1>> and <<ISO19157>>.
