
:sectnums:

////
== Conformance

=== General

This part of ISO {docnumber} defines four classes of requirements and
conformance. <<Annex-A>> specifies how conformance with these classes
shall be tested.

=== Address instance

Any address instance claiming conformance to this standard shall meet
the encoding rules specified in the abstract test suite in <<Annex-A-1>>.

=== Address profile register

To conform to this standard, an address profile register shall satisfy
all of the conditions specified in <<Annex-A-2>>.














////

=== IxAddressProfile

Any machine-readable description of an address profile conforming to
<<ISO19160-1>> which conformance is claimed shall pass all the
requirements described in the abstract test suite in <<Annex-A-2>>.

=== IxAddressClass

Any machine-readable description of a profile conforming to
<<ISO19160-1>> which conformance is claimed shall pass all the
requirements described in the abstract test suite in <<Annex-A-2>>.

=== IxAddressComponent

Any machine-readable description of a profile conforming to
<<ISO19160-1>> which conformance is claimed shall pass all the
requirements described in the abstract test suite in <<Annex-A-2>>.

=== IxAddressInstance

Any instance of IxAddressProfile class for which
IxAddressInstance conformance is claimed shall pass the requirements
described in the abstract test suite in <<Annex-A-2>>.

=== FormTemplate

Any FormTemplate in Interchange Address Profile model for which
FormTemplate conformance is claimed shall pass the requirements
described in the abstract test suite in <<Annex-A-2>>.

=== DisplayTemplate

Any DisplayTemplate in Interchange Address Profile model for
which DisplayTemplate conformance is claimed shall pass the
requirements described in the abstract test suite in <<Annex-A-2>>.
////