:sectnums:
== Conformance

=== General

This part of ISO {docnumber} defines four classes of requirements and
conformance. <<Annex-A>> specifies how conformance with these classes
shall be tested.

=== AddressProfileDescription

Any machine-readable description of a profile conforming to
<<ISO191601>> which conformance is claimed shall pass all the
requirements described in the abstract test suite in <<Annex-A-2>>.

=== AddressInstance

Any instance of AddressProfileDescription class for which
AddressInstance conformance is claimed shall pass the requirements
described in the abstract test suite in <<Annex-A-2>>.

=== AddressInputTemplate

Any AddressInputTemplate in address profile description model for which
AddressInputTemplate conformance is claimed shall pass the requirements
described in the abstract test suite in <<Annex-A-2>>.

=== AddressDisplayTemplate

Any AddressDisplayTemplate in address profile description model for
which AddressDisplayTemplate conformance is claimed shall pass the
requirements described in the abstract test suite in <<Annex-A-2>>.
