
[[ix-address-instance]]
== Interchange address instance

An interchange address instance is the representation of an address
that conforms to an interchange address class, which in turn
belongs to an interchange address profile.

An address instance is considered to conform to an interchange
address profile it is conforms to any of the profile's
address classes.

=== Attributes

ID:: unique identifier for this interchange address instance.

name:: a human-readable name for this interchange address instance.

profile:: the interchange address profile which contains
the interchange address class it conforms to.

addressClass:: the interchange address class it conforms to.

signature:: a cryptographic signature of the interchange
address instance itself together with its content.
Optional. Represented as a `Signature`.

validity:: time interval representing validity of the
interchange address instance.

applicability:: spatial representation of the geographic
area that this interchange address instance covers.
Optional, multiple allowed. `MD_SpatialRepresentation`.

displayTemplate:: display template that this interchange
address instance should be shown with. This allows an
address originator to provide a desired display view
of the address.


[[ix-address-instance-component]]
=== Interchange address instance component
// (IxAddressInstanceComponent)

An interchange address component instance represents a data value
for a corresponding interchange address component.

Each data value only applies to a single interchange
address component which belongs to an interchange address class.

==== Attributes

type:: the interchange address component the value is for.

values:: one or more values for the interchange address component
specified in `type`. The cardinality of this field depends on the
type of value. Represented as an `AddressComponentDataValue`.


==== Address component data value

A single value for the interchange address instance component.

type:: the data type of its value. A value from `AddressComponentDataType`.

value:: the value of the specified component. `CharacterString`.


[[ix-address-capability-instance]]
=== Address capability instance

The address capability instance is incorporated into an interchange
address instance to mark its capabilities as determined by an address
processor:

capability:: the particular address capability that has been fulfilled. Represented
by a `Uri` value that incorporates the address capability identifier with
the capability status value.

signature:: cryptographic signature used to ensure that the
capability is marked by an address process trusted for
verification of this capability.
The signature generated must incorporate the `id` attribute
of the interchange address instance that owns it.
Optional. Represented by `Signature`.

