@startuml

!include style.uml.inc

'******* CLASS DEFINITION *********************************************
!include LineElementReference.wsd

class DisplayTemplate {
  +lines: DisplayLine[0..*]
}

class DisplayLine {
  +elements: DisplayLineElementReference[0..*]
}

class DisplayLineElement{

}

class DataElement{
  +value: CharacterString
}

class TextElement{
  +text: CharacterString
}

'******* NOTES ********************************************************


'******* CLASS RELATIONS **********************************************

TextElement -up-|> DisplayLineElement
DataElement -up-|> DisplayLineElement
DisplayLine -up-> DisplayTemplate
DisplayLineElementReference -up-> DisplayLine
DisplayLineElement -up-> DisplayLineElementReference
@enduml