@startuml DisplayTemplate
/'
Diagram:        DisplayTemplate
DateCreate:     03/05/2019
Description:

Hystory of changes:
> DD/MM/YYYY
    -
    -
'/

'******* CONFIGURATION ************************************************
skinparam classAttributeIconSize 0
skinparam Dpi 150
skinparam Monochrome true
skinparam LineType ortho
skinparam nodesep 60
skinparam ranksep 30
hide circle
/' skinparam CircledCharacterRadius 0 '/
/' skinparam CircledCharacterFontSize 0 '/
skinparam Default {
TextAlignment center
FontName Helvetica
}
skinparam Class {
AttributeIconSize 0
BackgroundColor White
FontStyle bold
StereotypeFontSize 10
}
skinparam Rectangle {
BackgroundColor White
FontStyle bold
FontSize 11
StereotypeFontSize 10
}
skinparam Object {
BackgroundColor White
FontStyle bold
FontSize 11
StereotypeFontSize 10
}

skinparam Entity {
StereotypeFontSize 10
}

'******* CLASS DEFINITION *********************************************
class DisplayTemplate {
    +lines: DisplayLine[0..*]
}

class LayoutTemplate {
    +id: CharacterString
    +name: CharacterString
    +addressClass: InterchangeAddressClass
    +description: CharacterString
    +localization: Localization
    +dimensions: LayoutDimension[0..*]
    +orientation: LayoutOrientation[0..1]
    +lines: LayoutLine[0..*]
}

class DisplayLine {
    +elements: DisplayLineElementReference[0..*]
}

class LineElementReference {
    +target: InterchangeAddressComponent
    +name: CharacterString
    +description: CharacterString[0..1]
}

class DisplayLineElementReference {
    +values: DisplayLineElement[0..*]
}

class DisplayLineElement{

}

class DataElement{
    +value: CharacterString
}

class TextElement{
    +text: CharacterString
}

'******* NOTES ********************************************************


'******* CLASS RELATIONS **********************************************

DisplayTemplate -right-|> LayoutTemplate
DisplayLine -up-> DisplayTemplate
DisplayLine -right-|> LineElementReference
DisplayLineElementReference -up-> DisplayLine
DisplayLineElement -up-> DisplayLineElementReference
TextElement -up-> DisplayLineElement
DataElement -up-> DisplayLineElement

@enduml