@startuml

!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class FormTemplate {
  +lines: FormLine[0..*]
}

class LayoutTemplate{
  +id: CharacterString
  +name: CharacterString
  +addressClass: InterchangeAddressClass
  +description: CharacterString
  +localization: Localization
  +dimensions: LayoutDimension[0..*]
  +orientation: LayoutOrientation[0..1]
  +lines: LayoutLine[0..*]
}

class FormLine{
  +elements: FormLineElementReference[0..*]
}

class LineElementReference{
  +target: InterchangeAddressComponent
  +name: CharacterString
  +description: CharacterString[0..1]
}

class FormLineElementReference{
  +values: FormLineElement[0..*]
}

class FormLineElement{

}

class SelectionPair{
  +displayAs: CharacterString
  +key: CharacterString
}

class SelectionElement{
  +map: SelectionPair[1..*]
}

class DataElement{
  +value: CharacterString
}

class StaticTextElement{
  +value: CharacterString
}

class DataElementWithConditions{
  +conditions
}


'******* NOTES ********************************************************
note right of DataElementWithConditions: "ValueElementWithConditions\n are the conditions\n such as `zip code must be 5 digits long`, etc.\n Potentially use Object\n Constraint Language"

'******* CLASS RELATIONS **********************************************
FormTemplate -up-|> LayoutTemplate
FormLine -up--> FormTemplate
StaticTextElement -up-|> FormLineElement
SelectionElement -up-|> FormLineElement
DataElement -up-|> FormLineElement
DataElement <|-- DataElementWithConditions
FormLine -up-|> LineElementReference
FormLineElement -up-> FormLineElementReference
FormLineElementReference -up-> FormLine
SelectionPair -up-> SelectionElement
@enduml